[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "c4accounts"
version = "0.0.1"
description = "C4 Accounts Custom App"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pypika @ git+https://github.com/frappe/pypika@2c50e6142b2d61d2d243e466fdd5dc03b3d918f2"
]

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["c4accounts*"]
